name: PostgreSQL
on: push
jobs:
  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: timescale/timescaledb:latest-pg14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Setup database
        run: psql -h postgres -U postgres -c 'CREATE DATABASE "ci_bots";'
        env:
          PGPASSWORD: postgres
      - name: Run migration script
        run: psql -h postgres -d ci_bots -U postgres -f migration.sql
        env:
          PGPASSWORD: postgres
      - name: Query database - list all schemas
        run: psql -h postgres -d ci_bots -U postgres -c 'select schema_name from information_schema.schemata;'
        env:
          PGPASSWORD: postgres
      - name: Query database - list all tables in public schema
        run: psql -h postgres -d ci_bots -U postgres -c 'SELECT * FROM information_schema.tables WHERE table_schema = "public";'
        env:
          PGPASSWORD: postgres